SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
    FROM (SELECT *
            FROM APPOINTMENT
            WHERE APNT_YMD LIKE '2022-04-13%' AND (MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N')) A
    INNER JOIN PATIENT P ON A.PT_NO = P.PT_NO
    INNER JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
    ORDER BY A.APNT_YMD;
