SELECT YEAR, MONTH, GENDER, COUNT(*) AS "USERS"
    FROM (SELECT DISTINCT YEAR(N.SALES_DATE) AS "YEAR", MONTH(N.SALES_DATE) AS "MONTH", I.GENDER, I.USER_ID
            FROM USER_INFO I INNER JOIN ONLINE_SALE N
            ON I.USER_ID = N.USER_ID
            WHERE I.GENDER IS NOT NULL) A
    GROUP BY YEAR, MONTH, GENDER
    ORDER BY YEAR, MONTH, GENDER;
