SELECT YEAR, MONTH, COUNT(*) AS "PURCHASED_USERS", ROUND(COUNT(*)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS "PURCHASED_RATIO"
    FROM (SELECT DISTINCT YEAR(N.SALES_DATE) AS "YEAR", MONTH(N.SALES_DATE) AS "MONTH", N.USER_ID
            FROM ONLINE_SALE N INNER JOIN USER_INFO I
            ON N.USER_ID = I.USER_ID
            WHERE YEAR(I.JOINED) = 2021) A
    GROUP BY YEAR, MONTH
    ORDER BY YEAR, MONTH;
